### ISSUE TITLE
Dash Bio components for Julia

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#560]
Need to be generated and documented here, https://dash-julia.plotly.com

**Comment by rpkyle** [comment]
@HammadTheOne I'll build the components and push up to a branch for your review, shouldn't take me long.

**Comment by HammadTheOne** [comment]
@rpkyle  That sounds good, feel free to tag me in the PR/branch once it's opened :+1:

**Comment by rpkyle** [comment]
@HammadTheOne I saw a build time error from `dash-generate-components` that appears related to handling of some of the components from this repository -- I'm going to share it here, and will follow up if I identify the problem quickly with a potential solution:

```Traceback (most recent call last):
  File "/home/rpkyle/PlotlyRepos/venv/bin/dash-generate-components", line 8, in <module>
    sys.exit(cli())
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/component_generator.py", line 204, in cli
    generate_components(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/component_generator.py", line 120, in generate_components
    components = generate_classes_files(project_shortname, metadata, *generator_methods)
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_py_components_generation.py", line 155, in generate_classes_files
    generator(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 497, in generate_struct_file
    class_string = generate_class_string(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 448, in generate_class_string
    create_docstring_jl(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 272, in create_docstring_jl
    args="\n".join(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 273, in <genexpr>
    create_prop_docstring_jl(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 310, in create_prop_docstring_jl
    jl_type_name = get_jl_type(type_object=type_object)
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 238, in get_jl_type
    prop_type = js_to_jl_types[js_type_name]()
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 170, in <lambda>
    if get_jl_type(type_object["value"]) != ""
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 238, in get_jl_type
    prop_type = js_to_jl_types[js_type_name]()
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 131, in shape_or_exact
    "\n".join(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 132, in <genexpr>
    create_prop_docstring_jl(
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 310, in create_prop_docstring_jl
    jl_type_name = get_jl_type(type_object=type_object)
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 238, in get_jl_type
    prop_type = js_to_jl_types[js_type_name]()
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 155, in <lambda>
    ", ".join("{}".format(str(t["value"])) for t in type_object["value"])
  File "/home/rpkyle/PlotlyRepos/venv/lib/python3.8/site-packages/dash/development/_jl_components_generation.py", line 155, in <genexpr>
    ", ".join("{}".format(str(t["value"])) for t in type_object["value"])
TypeError: string indices must be integers
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dash-bio@0.7.0 build:backends: `dash-generate-components ./src/lib/components dash_bio -p package-info.json && dash-generate-components ./src/lib/components dash_bio -p package-info.json --r-prefix 'dashbio' --r-suggests 'dash,dashHtmlComponents,jsonlite,plotly' --jl-prefix 'dashbio'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dash-bio@0.7.0 build:backends script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rpkyle/.npm/_logs/2021-05-13T15_14_26_395Z-debug.log
```

**Comment by jackparmer** [comment]
Published and documented here: https://dash-julia.plotly.com/dash-bio
